version: '3.8'

services: 
  api:
    container_name: api
    image: taskmanager-api
    build:
      context: .
    ports:
      - '${API_PORT}:${API_PORT}'
    env_file: .env
    networks:
      - app-network
    command: ./wait-for-it.sh -t 0 postgres:${POSTGRES_PORT} -- npm run start:${NODE_ENV}

  postgres:
    container_name: postgres
    hostname: postgres
    image: 'postgres:13'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always
    env_file: .env
    networks:
      - app-network
    volumes:
      - postgresql_data:/var/lib/postgres/data
    

volumes:
  postgresql_data:
    driver: local

networks:
  app-network:
    driver: bridge