version: '3.8'

services: 
  api:
    container_name: api
    image: taskmanager-api
    build:
      context: .
    ports:
      - '3000:3000'
    env_file: .env
    depends_on: 
      - postgres

  postgres:
    container_name: postgres
    hostname: postgres
    image: 'postgres:13'
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    restart: always
    env_file: .env
    volumes:
      - postgresql_data:/var/lib/postgres/data

volumes:
  postgresql_data:
    driver: local